---
# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: readme

"on":
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Hub readme
        uses: actionhippie/pushrm@db8835668f770a1b8be17d19b5e6b36450c6766f # v1
        with:
          provider: dockerhub
          target: webhippie/minecraft-forge
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          description: Docker image for Minecraft Forge
          readme: README.md

      - name: Quay readme
        uses: actionhippie/pushrm@db8835668f770a1b8be17d19b5e6b36450c6766f # v1
        with:
          provider: quay
          target: quay.io/webhippie/minecraft-forge
          apikey: ${{ secrets.QUAY_APIKEY }}
          readme: README.md

...
